version: "3"

services:

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      # - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - .env/.postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/docker/volumes/edzeup/postgresql/_data

  web:
    build: .
    image: django
    container_name: django
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - django_data:/var/lib/docker/volumes/edzeup/django/_data
    env_file: .env/.django.env

volumes:
  postgres_data: {}
  django_data: {}